package com.dataport.wellness.utils;

import java.util.ArrayList;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

public class RichTextUtil {
    public static List<String> getRichTextImgListUtil(String richText){
        List<String> list = new ArrayList<>();
        String img = "";
        Pattern p_image;
        Matcher m_image;
        // String regEx_img = "<img.*src=(.*?)[^>]*?>"; //图片链接地址
        String regEx_img = "<img.*src\\s*=\\s*(.*?)[^>]*?>";
        p_image = Pattern.compile(regEx_img, Pattern.CASE_INSENSITIVE);
        m_image = p_image.matcher(richText);
        while (m_image.find()) {
            // 得到<img />数据
            img = m_image.group();
            // 匹配<img>中的src数据
            Matcher m = Pattern.compile("src\\s*=\\s*\"?(.*?)(\"|>|\\s+)").matcher(img);
            while (m.find()) {
                list.add(m.group(1));
            }
        }
        return list;
    }

    public static String getRichTextStr(String richText) {
        richText = richText.replaceAll("(<[^<]*?>)|(<[\\s]*?/[^<]*?>)|(<[^<]*?/[\\s]*?>)", "");
        richText = richText.replaceAll("&nbsp;", "");
        richText = richText.replaceAll("&iexcl;", "¡");
        richText = richText.replaceAll("&cent;", "¢");
        richText = richText.replaceAll("&pound;", "£");
        richText = richText.replaceAll("&curren;", "¤");
        richText = richText.replaceAll("&yen;", "¥");
        richText = richText.replaceAll("&brvbar;", "¦");
        richText = richText.replaceAll("&sect;", "§");
        richText = richText.replaceAll("&uml;", "¨");
        richText = richText.replaceAll("&copy;", "©");
        richText = richText.replaceAll("&ordf;", "ª");
        richText = richText.replaceAll("&laquo;", "«");
        richText = richText.replaceAll("&not;", "¬");
        richText = richText.replaceAll("&shy;", "");
        richText = richText.replaceAll("&reg;", "®");
        richText = richText.replaceAll("&macr;", "¯");
        richText = richText.replaceAll("&deg;", "°");
        richText = richText.replaceAll("&plusmn;", "±");
        richText = richText.replaceAll("&sup2;", "²");
        richText = richText.replaceAll("&sup3;", "³");
        richText = richText.replaceAll("&acute;", "´");
        richText = richText.replaceAll("&micro;", "µ");
        richText = richText.replaceAll("&para;", "¶");
        richText = richText.replaceAll("&middot;", "·");
        richText = richText.replaceAll("&cedil;", "¸");
        richText = richText.replaceAll("&sup1;", "¹");
        richText = richText.replaceAll("&ordm;", "º");
        richText = richText.replaceAll("&raquo;", "»");
        richText = richText.replaceAll("&frac14;", "¼");
        richText = richText.replaceAll("&frac12;", "½");
        richText = richText.replaceAll("&frac34;", "¾");
        richText = richText.replaceAll("&iquest;", "¿");
        richText = richText.replaceAll("&Agrave;", "À");
        richText = richText.replaceAll("&Aacute;", "Á");
        richText = richText.replaceAll("&Acirc;", "Â");
        richText = richText.replaceAll("&Atilde;", "Ã");
        richText = richText.replaceAll("&Auml;", "Ä");
        richText = richText.replaceAll("&Aring;", "Å");
        richText = richText.replaceAll("&AElig;", "Æ");
        richText = richText.replaceAll("&Ccedil;", "Ç");
        richText = richText.replaceAll("&Egrave;", "È");
        richText = richText.replaceAll("&Eacute;", "É");
        richText = richText.replaceAll("&Ecirc;", "Ê");
        richText = richText.replaceAll("&Euml;", "Ë");
        richText = richText.replaceAll("&Igrave;", "Ì");
        richText = richText.replaceAll("&Iacute;", "Í");
        richText = richText.replaceAll("&Icirc;", "Î");
        richText = richText.replaceAll("&Iuml;", "Ï");
        richText = richText.replaceAll("&ETH;", "Ð");
        richText = richText.replaceAll("&Ntilde;", "Ñ");
        richText = richText.replaceAll("&Ograve;", "Ò");
        richText = richText.replaceAll("&Oacute;", "Ó");
        richText = richText.replaceAll("&Ocirc;", "Ô");
        richText = richText.replaceAll("&Otilde;", "Õ");
        richText = richText.replaceAll("&Ouml;", "Ö");
        richText = richText.replaceAll("&times;", "×");
        richText = richText.replaceAll("&Oslash;", "Ø");
        richText = richText.replaceAll("&Ugrave;", "Ù");
        richText = richText.replaceAll("&Uacute;", "Ú");
        richText = richText.replaceAll("&Ucirc;", "Û");
        richText = richText.replaceAll("&Uuml;", "Ü");
        richText = richText.replaceAll("&Yacute;", "Ý");
        richText = richText.replaceAll("&THORN;", "Þ");
        richText = richText.replaceAll("&szlig;", "ß");
        richText = richText.replaceAll("&agrave;", "à");
        richText = richText.replaceAll("&aacute;", "á");
        richText = richText.replaceAll("&acirc;", "â");
        richText = richText.replaceAll("&atilde;", "ã");
        richText = richText.replaceAll("&auml;", "ä");
        richText = richText.replaceAll("&aring;", "å");
        richText = richText.replaceAll("&aelig;", "æ");
        richText = richText.replaceAll("&ccedil;", "ç");
        richText = richText.replaceAll("&egrave;", "è");
        richText = richText.replaceAll("&eacute;", "é");
        richText = richText.replaceAll("&ecirc;", "ê");
        richText = richText.replaceAll("&euml;", "ë");
        richText = richText.replaceAll("&igrave;", "ì");
        richText = richText.replaceAll("&iacute;", "í");
        richText = richText.replaceAll("&icirc;", "î");
        richText = richText.replaceAll("&iuml;", "ï");
        richText = richText.replaceAll("&eth;", "ð");
        richText = richText.replaceAll("&ntilde;", "ñ");
        richText = richText.replaceAll("&ograve;", "ò");
        richText = richText.replaceAll("&oacute;", "ó");
        richText = richText.replaceAll("&ocirc;", "ô");
        richText = richText.replaceAll("&otilde;", "õ");
        richText = richText.replaceAll("&ouml;", "ö");
        richText = richText.replaceAll("&divide;", "÷");
        richText = richText.replaceAll("&oslash;", "ø");
        richText = richText.replaceAll("&ugrave;", "ù");
        richText = richText.replaceAll("&uacute;", "ú");
        richText = richText.replaceAll("&ucirc;", "û");
        richText = richText.replaceAll("&uuml;", "ü");
        richText = richText.replaceAll("&yacute;", "ý");
        richText = richText.replaceAll("&thorn;", "þ");
        richText = richText.replaceAll("&yuml;", "ÿ");
        richText = richText.replaceAll("&fnof;", "ƒ");
        richText = richText.replaceAll("&Alpha;", "Α");
        richText = richText.replaceAll("&Beta;", "Β");
        richText = richText.replaceAll("&Gamma;", "Γ");
        richText = richText.replaceAll("&Delta;", "Δ");
        richText = richText.replaceAll("&Epsilon;", "Ε");
        richText = richText.replaceAll("&Zeta;", "Ζ");
        richText = richText.replaceAll("&Eta;", "Η");
        richText = richText.replaceAll("&Theta;", "Θ");
        richText = richText.replaceAll("&Iota;", "Ι");
        richText = richText.replaceAll("&Kappa;", "Κ");
        richText = richText.replaceAll("&Lambda;", "Λ");
        richText = richText.replaceAll("&Mu;", "Μ");
        richText = richText.replaceAll("&Nu;", "Ν");
        richText = richText.replaceAll("&Xi;", "Ξ");
        richText = richText.replaceAll("&Omicron;", "Ο");
        richText = richText.replaceAll("&Pi;", "Π");
        richText = richText.replaceAll("&Rho;", "Ρ");
        richText = richText.replaceAll("&Sigma;", "Σ");
        richText = richText.replaceAll("&Tau;", "Τ");
        richText = richText.replaceAll("&Upsilon;", "Υ");
        richText = richText.replaceAll("&Phi;", "Φ");
        richText = richText.replaceAll("&Chi;", "Χ");
        richText = richText.replaceAll("&Psi;", "Ψ");
        richText = richText.replaceAll("&Omega;", "Ω");
        richText = richText.replaceAll("&alpha;", "α");
        richText = richText.replaceAll("&beta;", "β");
        richText = richText.replaceAll("&gamma;", "γ");
        richText = richText.replaceAll("&delta;", "δ");
        richText = richText.replaceAll("&epsilon;", "ε");
        richText = richText.replaceAll("&zeta;", "ζ");
        richText = richText.replaceAll("&eta;", "η");
        richText = richText.replaceAll("&theta;", "θ");
        richText = richText.replaceAll("&iota;", "ι");
        richText = richText.replaceAll("&kappa;", "κ");
        richText = richText.replaceAll("&lambda;", "λ");
        richText = richText.replaceAll("&mu;", "μ");
        richText = richText.replaceAll("&nu;", "ν");
        richText = richText.replaceAll("&xi;", "ξ");
        richText = richText.replaceAll("&omicron;", "ο");
        richText = richText.replaceAll("&pi;", "π");
        richText = richText.replaceAll("&rho;", "ρ");
        richText = richText.replaceAll("&sigmaf;", "ς");
        richText = richText.replaceAll("&sigma;", "σ");
        richText = richText.replaceAll("&tau;", "τ");
        richText = richText.replaceAll("&upsilon;", "υ");
        richText = richText.replaceAll("&phi;", "φ");
        richText = richText.replaceAll("&chi;", "χ");
        richText = richText.replaceAll("&psi;", "ψ");
        richText = richText.replaceAll("&omega;", "ω");
        richText = richText.replaceAll("&thetasym;", "?");
        richText = richText.replaceAll("&upsih;", "?");
        richText = richText.replaceAll("&piv;", "?");
        richText = richText.replaceAll("&bull;", "•");
        richText = richText.replaceAll("&hellip;", "…");
        richText = richText.replaceAll("&prime;", "′");
        richText = richText.replaceAll("&Prime;", "″");
        richText = richText.replaceAll("&oline;", "‾");
        richText = richText.replaceAll("&frasl;", "⁄");
        richText = richText.replaceAll("&weierp;", "℘");
        richText = richText.replaceAll("&image;", "ℑ");
        richText = richText.replaceAll("&real;", "ℜ");
        richText = richText.replaceAll("&trade;", "™");
        richText = richText.replaceAll("&alefsym;", "ℵ");
        richText = richText.replaceAll("&larr;", "←");
        richText = richText.replaceAll("&uarr;", "↑");
        richText = richText.replaceAll("&rarr;", "→");
        richText = richText.replaceAll("&darr;", "↓");
        richText = richText.replaceAll("&harr;", "↔");
        richText = richText.replaceAll("&crarr;", "↵");
        richText = richText.replaceAll("&lArr;", "⇐");
        richText = richText.replaceAll("&uArr;", "⇑");
        richText = richText.replaceAll("&rArr;", "⇒");
        richText = richText.replaceAll("&dArr;", "⇓");
        richText = richText.replaceAll("&hArr;", "⇔");
        richText = richText.replaceAll("&forall;", "∀");
        richText = richText.replaceAll("&part;", "∂");
        richText = richText.replaceAll("&exist;", "∃");
        richText = richText.replaceAll("&empty;", "∅");
        richText = richText.replaceAll("&nabla;", "∇");
        richText = richText.replaceAll("&isin;", "∈");
        richText = richText.replaceAll("&notin;", "∉");
        richText = richText.replaceAll("&ni;", "∋");
        richText = richText.replaceAll("&prod;", "∏");
        richText = richText.replaceAll("&sum;", "∑");
        richText = richText.replaceAll("&minus;", "−");
        richText = richText.replaceAll("&lowast;", "∗");
        richText = richText.replaceAll("&radic;", "√");
        richText = richText.replaceAll("&prop;", "∝");
        richText = richText.replaceAll("&infin;", "∞");
        richText = richText.replaceAll("&ang;", "∠");
        richText = richText.replaceAll("&and;", "∧");
        richText = richText.replaceAll("&or;", "∨");
        richText = richText.replaceAll("&cap;", "∩");
        richText = richText.replaceAll("&cup;", "∪");
        richText = richText.replaceAll("&int;", "∫");
        richText = richText.replaceAll("&there4;", "∴");
        richText = richText.replaceAll("&sim;", "∼");
        richText = richText.replaceAll("&cong;", "∝");
        richText = richText.replaceAll("&asymp;", "≈");
        richText = richText.replaceAll("&ne;", "≠");
        richText = richText.replaceAll("&equiv;", "≡");
        richText = richText.replaceAll("&le;", "≤");
        richText = richText.replaceAll("&ge;", "≥");
        richText = richText.replaceAll("&sub;", "⊂");
        richText = richText.replaceAll("&sup;", "⊃");
        richText = richText.replaceAll("&nsub;", "⊄");
        richText = richText.replaceAll("&sube;", "⊆");
        richText = richText.replaceAll("&supe;", "⊇");
        richText = richText.replaceAll("&oplus;", "⊕");
        richText = richText.replaceAll("&otimes;", "⊗");
        richText = richText.replaceAll("&perp;", "⊥");
        richText = richText.replaceAll("&sdot;", "⋅");
        richText = richText.replaceAll("&lceil;", "?");
        richText = richText.replaceAll("&rceil;", "?");
        richText = richText.replaceAll("&lfloor;", "?");
        richText = richText.replaceAll("&rfloor;", "?");
        richText = richText.replaceAll("&lang;", "?");
        richText = richText.replaceAll("&rang;", "?");
        richText = richText.replaceAll("&loz;", "◊");
        richText = richText.replaceAll("&spades;", "♠");
        richText = richText.replaceAll("&clubs;", "♣");
        richText = richText.replaceAll("&hearts;", "♥");
        richText = richText.replaceAll("&diams;", "♦");
        richText = richText.replaceAll("&quot;", "'");
        richText = richText.replaceAll("&amp;", "");
        richText = richText.replaceAll("&lt;", "<");
        richText = richText.replaceAll("&gt;", ">");
        richText = richText.replaceAll("&OElig;", "Œ");
        richText = richText.replaceAll("&oelig;", "œ");
        richText = richText.replaceAll("&Scaron;", "Š");
        richText = richText.replaceAll("&scaron;", "š");
        richText = richText.replaceAll("&Yuml;", "Ÿ");
        richText = richText.replaceAll("&circ;", "ˆ");
        richText = richText.replaceAll("&tilde;", "˜");
        richText = richText.replaceAll("&ensp;", "");
        richText = richText.replaceAll("&emsp;", "");
        richText = richText.replaceAll("&thinsp;", "");
        richText = richText.replaceAll("&zwnj;", "");
        richText = richText.replaceAll("&zwj;", "‍");
        richText = richText.replaceAll("&‎lrm;", "");
        richText = richText.replaceAll("&rlm;", "");
        richText = richText.replaceAll("&ndash;", "–");
        richText = richText.replaceAll("&mdash;", "—");
        richText = richText.replaceAll("&lsquo;", "‘");
        richText = richText.replaceAll("&rsquo;", "’");
        richText = richText.replaceAll("&sbquo;", "‚");
        richText = richText.replaceAll("&ldquo;", "“");
        richText = richText.replaceAll("&rdquo;", "”");
        richText = richText.replaceAll("&bdquo;", "„");
        richText = richText.replaceAll("&dagger;", "†");
        richText = richText.replaceAll("&Dagger;", "‡");
        richText = richText.replaceAll("&permil;", "‰");
        richText = richText.replaceAll("&lsaquo;", "‹");
        richText = richText.replaceAll("&rsaquo;", "›");
        richText = richText.replaceAll("&euro;", "€");

        return richText;
    }

}
